language: python
cache: pip
python:
  - "3.6"
  - "3.7"
  - "3.8"
env:
  - TEST_TYPE="tests"
    INSTALL_TYPE="dev"
  - TEST_TYPE="tests"
    INSTALL_TYPE="dev_sdist"
  - TEST_TYPE="tests"
    INSTALL_TYPE="dev_bdist_wheel"
jobs:
  include:
    - python: "3.7"
      env:
        - TEST_TYPE="precommit"
          INSTALL_TYPE="dev"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq liblapack3 liblapack-dev
install:
  - ./.travis-data/install_script.sh
script:
  - ./.travis-data/test_script.sh
after_success:
  - codecov
