#!/usr/bin/env python

# (c) 2015-2018, ETH Zurich, Institut fuer Theoretische Physik
# Author: Dominik Gresch <greschd@gmx.ch>
"""
Tests for the 'symmetrize' CLI command.
"""

import tempfile

from click.testing import CliRunner

import tbmodels
from tbmodels._cli import cli


def test_cli_symmetrize(
    models_close,
    sample,
    cli_sparsity_arguments,
    cli_verbosity_argument,
    modify_reference_model_sparsity,
):
    """
    Test the 'symmetrize' command.
    """
    runner = CliRunner()
    with tempfile.NamedTemporaryFile() as out_file:
        run = runner.invoke(
            cli,
            [
                "symmetrize",
                "-o",
                out_file.name,
                "-s",
                sample("InAs_symmetries.hdf5"),
                "-i",
                sample("InAs_nosym.hdf5"),
            ]
            + cli_sparsity_arguments
            + cli_verbosity_argument,
            catch_exceptions=False,
        )
        print(run.output)
        model_res = tbmodels.Model.from_hdf5_file(out_file.name)
    model_reference = tbmodels.Model.from_hdf5_file(sample("InAs_sym_reference.hdf5"))
    modify_reference_model_sparsity(model_reference)
    models_close(model_res, model_reference)


def test_invalid_symmetries_file(sample):
    """
    Test the error generated by the 'symmetrize' command when an invalid
    symmetries file is supplied.
    """
    runner = CliRunner(mix_stderr=False)
    with tempfile.NamedTemporaryFile() as out_file:
        run = runner.invoke(
            cli,
            [
                "symmetrize",
                "-o",
                out_file.name,
                "-s",
                sample("InAs_nosym.hdf5"),
                "-i",
                sample("InAs_nosym.hdf5"),
            ],
            catch_exceptions=False,
        )
    assert run.stderr.startswith("Error: [INVALID_SYMMETRY_TYPE]")


def test_positions_not_symmetric(sample):
    """
    Test the error generated by the 'symmetrize' command when an invalid
    symmetries file is supplied.
    """
    runner = CliRunner(mix_stderr=False)
    with tempfile.NamedTemporaryFile() as out_file:
        run = runner.invoke(
            cli,
            [
                "symmetrize",
                "-o",
                out_file.name,
                "-s",
                sample("InAs_symmetries.hdf5"),
                "-i",
                sample("InAs_positions_wrong.hdf5"),
            ],
            catch_exceptions=False,
        )
    assert run.stderr.startswith("Error: [POSITIONS_NOT_SYMMETRIC]")
